### ISSUE TITLE
Default Ruby encoding is US-ASCII, which breaks jekyll-sass-converter

### ISSUE THREAD

**Issue by tbroyer** [Starefossen/docker-github-pages#2]
If you use `docker-compose up` (or your favorite `docker run` command) to run https://github.com/ozwillo/ozwillo-doc/commit/6ac35f6252453587868f7dc9ad591acaf9741778, you'll see that the processing fails with:
```
  Conversion error: Jekyll::Converters::Scss encountered an error while converting 'css/main.scss':
                    Invalid US-ASCII character "\xC3" on line 68
```

SASS defaults to the Ruby default encoding (unless it's `ASCII-8BIT` in which case it defaults to UTF-8; see https://github.com/sass/sass/blob/3.4.21/lib/sass/util.rb#L862-L902), and in the Docker image it apparently defaults to `US-ASCII`.

In this case, there's fortunately a workaround: prepend `@charset "UTF-8";` or a UTF-8 BOM to each SCSS file, but still: the workaround isn't needed on GitHub infra.

**Comment by Starefossen** [comment]
Possibly related to this issue: jekyll-sass-converter/pull#39 jekyll/jekyll#2853

**Comment by tbroyer** [comment]
Actually no: the files don't have a BOM, and the error points to a line containing a non-ASCII char.

**Comment by Starefossen** [comment]
Ok, this issue jekyll/jekyll#4268 seams more like it, don't you think?

I am pushing `starefossen/github-pages:utf8` to Docker Hub, would you mind pulling that down and giving it a try without the prepended `@charset "UTF-8";`?

**Comment by tbroyer** [comment]
`starefossen/github-pages:utf8` fixes the issue, thanks!

(BTW, I noticed Jekyll provides Docker images based on Alpine whereas yours is based on Ubuntu; Jekyll's image is 151M according to imagelayers.io, while yours is 846.1M for `latest` and 877.5M for `utf8`; do you think you could possibly move to Alpine as a base image, or maybe even jekyll/jekyll? Maybe I should create a new issue…)

Anyway, thanks for that image!

**Comment by tbroyer** [comment]
Oh, just found out about the `jekyll/jekyll:pages` image; so I think I'll just make the switch. Thanks anyway!

**Comment by Starefossen** [comment]
Thanks for the heads about `jekyll/jekyll:pages`, that did not exist when I created this Image.
