### ISSUE TITLE
Last tag on Docker Hub is 177

### ISSUE THREAD

**Issue by thaJeztah** [Starefossen/docker-github-pages#64]
I noticed that the last tag on Docker Hub is `:177` (https://hub.docker.com/r/starefossen/github-pages/tags). Wondering if a newer tag can be published (or an automated build set-up, so that a new version is automatically published when tagged on GitHub).

@Starefossen

**Comment by Starefossen** [comment]
Not sure why Docker Hub dind't tag the last ones correctly but I have built and tagged `:198` now 😄

**Comment by thaJeztah** [comment]
Thanks!!
